.\" Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.\" Please adjust this date whenever revising the manpage.
.\" 
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.TH "UADE" "1" "2005-11-16" "Heikki Orsila and Michael Doering" ""
.SH "NAME"
UADE \- Unix Amiga Delitracker Emulator
.SH "SYNOPSIS"
.B uade123
[\fIoptions\fR] \fIfiles\fR ...
.SH "DESCRIPTION"
uade123 plays old amiga music formats by emulating Amiga hardware. The system
reimplements Eagleplayer API and some AmigaOS to use existing Motorol 68000
binary plugins.
.SH "COMMAND LINE OPTIONS"

\fB\-1, \-\-one\fR
Play at most one subsong per file.
.TP
\fB\-@\fR filename\fB, \-\-list=\fRfilename
Play song files listed in the file.
.TP
\fB\-d\fR
Turn debug mode on. Experts only.
.TP
\fB\-e\fR format
Set output file format. Use with
.BR -f .
.TP
\fB\-f\fR filename
Output sound data to filename.
.TP
\fB\-\-filter\fR
Enable filter emulation. Default is ON.
.TP
\fB\-\-filter=\fRx
Set filter emulation mode to x. x is one of following: a500, a500e, a1200,
or a1200e. The default is a1200. PLEASE note that this option has an audible
effect even if a song doesn't use filtering at all, because A500 does some
filtering regardless of LED state.
.TP
\fB\-\-force\-led=\fRx
Turn Amiga filter on or off. 0 means off and 1 means on. The default is off
(0).
.TP
\fB\-g, \-\-get\-info\fR
Print playername and subsong information to stdout and then exit. This is
useful for recording script.
.TP
\fB\-h, \-\-help\fR
Print command line help.
.TP
\fB\-\-headphone\fR
Enable headphone postprocessing effect.
.TP 
\fB\-i,	\-\-ignore\fR
Force eagleplayer to play the song.
.TP
\fB\-\-interpolator=\fRs
Set interpolator to
.BR s .
It should be
.BR default ,
.BR cspline ,
or
.BR ansi .
cspline interpolator is bad for chip songs. It is designed for natural
sounding samples.
.TP
\fB\-j\fR x\fB, \-\-jump=\fRx
Jump to song position of x seconds.
\fB\-k, \-\-keys\fR
Enable action keys.
.TP
\fB\-K, \-\-no\-keys\fR
Disable action keys.
.TP
\fB\-m\fR filename
Set module filename.
.TP
\fB\-n, \-\-no-filter\fR
Disable filter emulation.
.TP 
\fB\-\-no\-song\-end\fR
Play music ad infinitum by ignoring songend.
.TP 
\fB\-p\fR x, \-\-panning=\fRx
Set panning effect to x. This means mixing left and right channel affinely
together. n is a value between 0 and 2. 0 is full stereo, 1 is mono, and
2 is inverse stereo.
.TP 
\fB\-P\fR playerfile
Set filename of the eagleplayer.
.TP 
\fB\-r, \-\-recursive\fR
Play directories recursively.
.TP 
\fB\-s\fR n\fB, \-\-subsong=\fRn
Choose subsong n.
.TP 
\fB\-S\fR scorefile
Set filename of sound core. Experts only. Useful for debugging sound core
related problems. Picking score file from earlier releases may help revealing
the problem source.
.TP 
\fB\-\-speed\-hack\fR
Enable speedhack. Emulate all instructions to be executed
in one m68k cycle. Some players, such as EMS v6, take too
many m68k cycles to be real\-time. This option gives them
enough m68k cycles. Notice that you do _not_ need to use this
switch with EMS v6 or Octamed, because it is automatically enabled for
those formats. A replayer usually knows to ask for speedhack.
.TP
\fB\-\-stderr\fR
Print all messages on stderr. This is useful if one uses -f /dev/stdout as
a trick to pipe sample data on the command line.
.TP 
\fB\-t\fR x\fB, \-\-timeout=\fRx
Set song time out to x seconds. Default is infinite (-1).
.TP 
\fB\-w\fR x\fB, \-\-subsong\-timeout=\fRx
Set subsong timeout to x seconds. -1 means infinite. Default is 512 seconds.
.TP
\fB\-v, \-\-verbose\fR
Turn verbose mode on. This is useful for debugging strange situations.
.TP 
\fB\-y\fR x\fB, \-\-silence\-timeout=\fRx.
Set silence timeout to x seconds. If x seconds of silence is detected the
(sub)song ends.
.TP 
\fB\-z, \-\-shuffle\fR
Turn shuffle mode on. Plays songs in random order.
.SH ACTION KEYS
uade123 can be controlled interactively on the command line by pressing
specific action keys.
.br
 [0-9]         Change subsong.
.br
 '.'           Skip 10 seconds forward.
.br
 SPACE, 'b'    Go to next subsong.
.br
 'c'           Pause.
.br
 'f'           Toggle filter (takes filter control away from eagleplayer).
.br
 'h'           Print this list.
.br
 'H'           Toggle headphones effect.
.br
 RETURN, 'n'   Next song.
.br
 'p'           Toggle postprocessing effects.
.br
 'P'           Toggle panning effect. Default value is 0.7.
.br
 'q'           Quit.
.br
 's'           Toggle between shuffle mode and normal play.
.br
 'v'           Toggle verbose mode.
.br
 'x'           Restart current subsong.
.br
 'z'           Previous subsong.
.SH CONFIGURATION FILES
To be written. Look at the example, and see
sourcedir/doc/eagleplayer.conf.
.SH "SUPPORTED FORMATS"
Quite a few. See documentation, eagleplayer.conf, and players/ directory.
.SH "FILES"
.TP 
PREFIX/bin/uade123
Player executable.
.TP
PREFIX/share/uade2/eagleplayer.conf
File containing name extensions and hints about different formats.
.TP 
PREFIX/share/uade2/score
MC68000 sound core file
.TP 
PREFIX/share/uade2/players
MC68000 eagleplayer binaries
.TP
PREFIX/share/uade2/uade.conf
Configuration file for UADE.
.TP
PREFIX/share/uade2/uaerc
Configuration file for UAE.
.TP
PREFIX/share/doc/uade-*
UADE documentation
.TP
PREFIX/share/man/man1/uade123.1
This man page.
.SH "EXAMPLES"
.TP 
\fBuade123 \-zr /path\fR
.br 
Play files under /path recursively in random order.
.SH "AUTHOR"
\fBUADE\fP project was started by Heikki Orsila <heikki.orsila@iki.fi>.
There have been many other contributors. Most notable contributors
are Michael 'mld' Doering (for almost anything),
Harry 'Piru' Sintonen (MorphOS port), and Antti S. Lankila <alankila@bel.fi>
(Amiga filter emulation). See
.B http://zakalwe.virtuaalipalvelin.net/uade
.br
for more information.
