#ifndef _AMIGAMSG_H_
#define _AMIGAMSG_H_

#define AMIGAMSG_REBOOT 1
#define AMIGAMSG_SETSUBSONG 2
#define AMIGAMSG_SONG_END 4
#define AMIGAMSG_PLAYERNAME 6
#define AMIGAMSG_MODULENAME 7
#define AMIGAMSG_SUBSINFO 9
#define AMIGAMSG_CHECKERROR 10
#define AMIGAMSG_SCORECRASH 11
#define AMIGAMSG_SCOREDEAD 12
#define AMIGAMSG_GENERALMSG 13
#define AMIGAMSG_NTSC 14
#define AMIGAMSG_FORMATNAME 15
#define AMIGAMSG_LOADFILE 16
#define AMIGAMSG_READ 17
#define AMIGAMSG_FILESIZE 18
#define AMIGAMSG_TIME_CRITICAL 19
#define AMIGAMSG_NO_INTERACTION 20
#define AMIGAMSG_TOGGLE_LED 21
#define AMIGAMSG_GET_INFO 22

#endif
