#ifndef _UADEIPC_H_
#define _UADEIPC_H_

#include <stdint.h>

enum uade_command {
  UADE_COMMAND_FIRST = 0,
  UADE_COMMAND_CONFIG,
  UADE_COMMAND_SCORE,
  UADE_COMMAND_PLAYER,
  UADE_COMMAND_MODULE,
  UADE_COMMAND_SUBSONG,
  UADE_COMMAND_PLAY,
  UADE_COMMAND_READ,
  UADE_COMMAND_REBOOT,
  UADE_COMMAND_LAST
};

enum uade_reply {
  UADE_REPLY_MSG = 1,
  UADE_REPLY_CANT_PLAY,
  UADE_REPLY_SONG_END,
  UADE_REPLY_CRASH,
  UADE_REPLY_SUBSONG_INFO,
  UADE_REPLY_PLAYERNAME,
  UADE_REPLY_MODULENAME,
  UADE_REPLY_FORMATNAME,
  UADE_REPLY_DATA,
};

struct uade_control {
  uint32_t command;
  uint32_t size;
  uint8_t data[];
} __attribute__((packed));

#endif
